import { getLang } from "../i18n";

const labelMapJP: Record<string, string> = {
  gills: "ひだ",
  pores: "管孔",
  spines: "針",
  ridges: "しわひだ",
  hollow: "中空",
  solid: "中実",
  present: "あり",
  absent: "なし",
  none: "なし",
  cortina: "蜘蛛の巣状",
  deadwood: "枯れ木",
  downed: "倒木",
  live: "生木",
  soil: "地面",
  broadleaf: "広葉樹",
  conifer: "針葉樹",
  mixed: "混生林",
  bamboo: "竹林",
  park: "公園",
  red: "赤",
  purple: "紫",
  white: "白",
  yellow: "黄",
  brown: "茶",
  black: "黒",
  gray: "グレー",
  orange: "橙",
  green: "緑",
  blue: "青",
  pink: "ピンク",
  other: "その他",
  N: "北",
  NE: "北東",
  E: "東",
  SE: "南東",
  S: "南",
  SW: "南西",
  W: "西",
  NW: "北西",
  valley: "沢",
  ridge: "尾根",
  flat: "平地",
  slope: "斜面",
};

const labelMapEN: Record<string, string> = {
  gills: "Gills",
  pores: "Pores",
  spines: "Spines",
  ridges: "Ridges",
  hollow: "Hollow",
  solid: "Solid",
  present: "Present",
  absent: "Absent",
  none: "None",
  cortina: "Cortina",
  deadwood: "Dead Wood",
  downed: "Downed Log",
  live: "Living Tree",
  soil: "Soil",
  broadleaf: "Broadleaf",
  conifer: "Conifer",
  mixed: "Mixed Forest",
  bamboo: "Bamboo",
  park: "Park",
  red: "Red",
  purple: "Purple",
  white: "White",
  yellow: "Yellow",
  brown: "Brown",
  black: "Black",
  gray: "Gray",
  orange: "Orange",
  green: "Green",
  blue: "Blue",
  pink: "Pink",
  other: "Other",
  N: "N",
  NE: "NE",
  E: "E",
  SE: "SE",
  S: "S",
  SW: "SW",
  W: "W",
  NW: "NW",
  valley: "Valley",
  ridge: "Ridge",
  flat: "Flat",
  slope: "Slope",
};

export const labelJP = (v?: string) => {
  return labelMapJP[v ?? ""] ?? v ?? "";
};

export const getLabel = (v?: string) => {
  const lang = getLang();
  const map = lang === "ja" ? labelMapJP : labelMapEN;
  return map[v ?? ""] ?? v ?? "";
};
